// Generated by CoffeeScript 1.6.3

/* Classe person */

(function() {
  var Aluno, Person,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Person = (function() {
    function Person() {
      this.firstName = 'Patrick';
      this.lastName = 'Steele';
    }

    Person.prototype.fullName = function() {
      this.teste = 'teste';
      return this.firstName + ' ' + this.lastName;
    };

    return Person;

  })();

  Aluno = (function(_super) {
    __extends(Aluno, _super);

    function Aluno() {
      this.teste();
    }

    Aluno.prototype.teste = function() {};

    return Aluno;

  })(Person);

  alert('aaaaaaeeeeeeee');

}).call(this);
